### ISSUE TITLE
movable camera project plan

### ISSUE THREAD

**Issue by rlho** [open-eyebeam/client#63]
## TODO
- [x] Create prototype
- [ ] Deploy to server
- [ ] iframe to open eyebeam
- [ ] Create something for the operated user

**Comment by rlho** [comment]
### Create something for the operated user


![Image](https://github.com/open-eyebeam/client/assets/5990045/19c6190f-30e9-4916-92a0-98b301e38afc)

**Comment by rlho** [comment]
### Create prototype



![Image](https://github.com/open-eyebeam/client/assets/5990045/59a35de4-f740-4fed-a440-ab6d3caa534e)
![Image](https://github.com/open-eyebeam/client/assets/5990045/69dceab1-af0f-4b3f-982a-b0ab19027264)
![Image](https://github.com/open-eyebeam/client/assets/5990045/8157552f-32c3-4718-8c1e-dc2d75888b59)
